### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Hueristic** [ecortesg/fantasy-score-gap#2]
Option to compare different size leagues.

**Comment by ecortesg** [comment]
Hey, thanks for reaching out. Can you expand a little bit? What exactly would you like to see?

**Comment by Hueristic** [comment]
I'm working on adjust positional draft strategy's moving from different size leagues and think your tool might come in handy if that option was available.

**Comment by ecortesg** [comment]
I see. So you would have roster settings for both League 1 and League 2. But then what? How would you compare positional balance between the two? Maybe have 24 WRs in League 1 and 36 WRs in League 2, and compare the graph and radar chart?

**Comment by Hueristic** [comment]
Sorry, I'll have to go back and take a closer look. I've gone through so many tools last week I forgot the specifics of this one.
